FROM centos:latest

MAINTAINER Knowledgeshare99

LABEL Remarks="This is a dockerfile example for Linux system"

RUN yum -y update && yum -y install httpd && yum clean all

#COPY data/httpd.conf /etc/httpd/conf/httpd.conf

#ADD data/html.tar.gz /var/www/html/

EXPOSE 80

#ENV HOME /root

#WORKDIR /root

#ENTRYPOINT ["ping"]
CMD ["/usr/sbin/httpd", "-D", "FOREGROUND"]
#CMD ["echo","Hello google.com"]
